### ISSUE TITLE
Initialize trader repository

### ISSUE THREAD

**Issue by Right2Drive** [agriculture-capstone/agritrader#12]
## Description
Initialize the repository. If we use Facebook's boilerplate we have to decide whether to eject or not

## Review
Enoch

## QA
James

**Comment by beaesguerra** [comment]
Things to Consider:
- might be worthwhile getting it set up and put in the app store (so we make sure that the base app is deployable to the app store)

**Comment by beaesguerra** [comment]
Notes:
Followed this guide to start react-native app: https://facebook.github.io/react-native/docs/getting-started.html
Followed this guide to integrate typescript: https://github.com/Microsoft/TypeScript-React-Native-Starter

**Comment by jeinglis** [comment]
Looks good although it took me a long time to get all my env variables set up so that it will launch (i didn't see the other tab that told you how to do it all) had to set ANDROID_HOME ---> android sdk and add adb.exe to my path. I think you should add these to the readme to make it easier for the others
